import new1 from './img/new1.png';
export const newsL = [
    {
        id: 1, 
        imgURL: new1,
        title: 'Time Management With Compassion: Tips To Recharge After Thanksgiving',
        author: 'Luciana Paulise',
        content: 'Thanksgiving week often brings a mix of joy and chaos. Between work deadlines, holiday preparations, and family commitments, it’s easy to feel overwhelmed. Balancing productivity with personal well-being is challenging, but it’s not impossible if you start applying compassion. My upcoming book introduces five core principles to help professionals manage their time more effectively: Timeboxing, Focus, Flow, Finish, and Compassion. While each principle offers a practical solution to common time management challenges, Compassion is especially relevant this holiday season.Why Compassion Matters for Time Management. Passion drives many of us to excel in our careers and personal lives but can also lead to overcommitment and burnout. The principle of Compassion invites us to honor our limits, recognize our needs, and approach time management with a sense of balance and self-care. When I was writing this book, I reached a point where I felt completely stuck. I knew exactly what I wanted to write, but I couldn’t find the time or motivation to finish it. It was frustrating—I kept thinking, “As the author of a time management book, I should be better at managing my time!” While that was true, as a coach, I also knew there was more going on. The truth was, I was exhausted. My drive to finish the book was pushing me beyond my limits, and I wasn’t taking the time to check in with how I was really feeling. I was tired, stressed, and overwhelmed by everything else happening in my life at the time. That’s when I realized I needed to practice what I preach and focus on self-compassion. This experience became the foundation for one of the most important parts of this book: the principle of Compassion. It reminded me that productivity isn’t just about working harder or faster—it’s also about respecting your own limits and making room for balance.'
    }, 
    {
        id: 2, 
        imgURL: new1,
        title: 'Time Management With Compassion: Tips To Recharge After Thanksgiving',
        author: 'Luciana Paulise',
        content: 'Thanksgiving week often brings a mix of joy and chaos. Between work deadlines, holiday preparations, and family commitments, it’s easy to feel overwhelmed. Balancing productivity with personal well-being is challenging, but it’s not impossible if you start applying compassion. My upcoming book introduces five core principles to help professionals manage their time more effectively: Timeboxing, Focus, Flow, Finish, and Compassion. While each principle offers a practical solution to common time management challenges, Compassion is especially relevant this holiday season.Why Compassion Matters for Time Management. Passion drives many of us to excel in our careers and personal lives but can also lead to overcommitment and burnout. The principle of Compassion invites us to honor our limits, recognize our needs, and approach time management with a sense of balance and self-care. When I was writing this book, I reached a point where I felt completely stuck. I knew exactly what I wanted to write, but I couldn’t find the time or motivation to finish it. It was frustrating—I kept thinking, “As the author of a time management book, I should be better at managing my time!” While that was true, as a coach, I also knew there was more going on. The truth was, I was exhausted. My drive to finish the book was pushing me beyond my limits, and I wasn’t taking the time to check in with how I was really feeling. I was tired, stressed, and overwhelmed by everything else happening in my life at the time. That’s when I realized I needed to practice what I preach and focus on self-compassion. This experience became the foundation for one of the most important parts of this book: the principle of Compassion. It reminded me that productivity isn’t just about working harder or faster—it’s also about respecting your own limits and making room for balance.'
    }, 


]
